server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/bakery_db
spring.datasource.username=postgres
spring.datasource.password=@aDN2shzSD1
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect